// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetElement(arg1:string):Promise<main.ElementInfo>;

export function GetIceRule(arg1:string):Promise<main.IceRuleInfo>;

export function GetRule(arg1:string):Promise<main.RuleInfo>;

export function GetSidebarTree():Promise<Array<main.TreeNode>>;

export function GetSnippet(arg1:string):Promise<main.SnippetInfo>;

export function GetStats():Promise<{[key: string]: number}>;

export function GetWixError(arg1:string):Promise<main.ErrorInfo>;

export function Search(arg1:string):Promise<Array<main.SearchResult>>;
