// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetElement(arg1) {
  return window['go']['main']['App']['GetElement'](arg1);
}

export function GetIceRule(arg1) {
  return window['go']['main']['App']['GetIceRule'](arg1);
}

export function GetRule(arg1) {
  return window['go']['main']['App']['GetRule'](arg1);
}

export function GetSidebarTree() {
  return window['go']['main']['App']['GetSidebarTree']();
}

export function GetSnippet(arg1) {
  return window['go']['main']['App']['GetSnippet'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetWixError(arg1) {
  return window['go']['main']['App']['GetWixError'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
